name: QA / Lint (Biome)

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Run Biome
        run: bunx @biomejs/biome ci src/