name: QA / Lint (Biome)

on:
  push:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11
      - name: Run Biome
        run: bunx @biomejs/biome ci src/